import {Router} from "express";
import { getAllClientes, getClienteByRut, createCliente, updateCliente, deleteCliente } from "../controllers/clientes.controller.js";
import { validarSchema } from "../middlewares/validarSchema.middleware.js";
import { clienteSchema } from "../schemas/clientes.schemas.js";
import { verificarToken, verificarRol } from "../middlewares/verificarToken.middleware.js";
import { token } from "morgan";
const router= Router();
router.post("/Cliente",verificarToken, validarSchema(clienteSchema), createCliente);
router.get("/Cliente",verificarToken, getAllClientes);
router.get("/Cliente/:Rut",verificarToken, getClienteByRut);
router.patch("/Cliente/:id",verificarToken, validarSchema(clienteSchema.partial()), updateCliente);
router.delete("/Cliente/:id",verificarToken, deleteCliente);
export default router;
